# Generated by Django 5.2.7 on 2025-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangarinorg', '0004_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='sub_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
